easy_admin:
    entities:
        Buffs:
            class: App\Entity\Buffs
            image_base_path: '/images/buffs/'
            form:
              fields:
                - "Name"
                - "Description"
                - "Value"
                - "StatEffect"
                - { property: "imageFile", type: "vich_image"}
                - "buffskills"'/images/buffs/'
            list:
              fields:
                - "Name"
                - "Description"
                - "Value"
                - "StatEffect"
                - { property: "Image", type: "image"}
                - "buffskills"
        Debuffs:
            class: App\Entity\Debuffs
            image_base_path: '/images/debuffs/'
            form:
              fields:
                - "Name"
                - "Description"
                - "Value"
                - "StatEffect"
                - { property: "imageFile", type: "vich_image"}
                - "debuffskills"
            list:
              fields:
                - "Name"
                - "Description"
                - "Value"
                - "StatEffect"
                - { property: "Image", type: "image"}
                - "debuffskills"
        OtherEffect:
            class: App\Entity\OtherEffect
            form:
              fields:
                - { property: "imageFile", type: "vich_image"}
        Skill:
            class: App\Entity\Skill
            image_base_path: '/images/skills/'
            list:
              fields:
                - "id"
                - "Name"
                - "Element"
                - "SkillUp"
                - "Buffs"
                - "Debuffs"
                - "OtherEffect"
                - "Passif"
                - "SkillAwake"
                - "State"
                - "LeaderSkill"
                - "mobs"
                - { property: "Image", type: "image"}
            form:
              fields:
                - "Name"
                - "Description"
                - "SkillUp"
                - "Passif"
                - "SkillAwake"
                - "Element"
                - "Buffs"
                - "Debuffs"
                - "OtherEffect"
                - "State"
                - "LeaderSkill"
                - "mobs"
                - { property: "imageFile", type: "vich_image"}
        Mob:
          class: App\Entity\Mob
          image_base_path : '/images/monstres/'
          form:
            fields:
              - "IDinGame"
              - "Name"
              - { property: "imageFile", type: "vich_image"}
              - "GradeNat"
              - "Family"
              - "Class"
              - "Attribute"
              - "Skills"
              - "Runes"
              - "Account"
              - "Stats"
              - "Devilmon"
              - "Awake"

          list:
            fields:
              - "Name"
              - { property: "Image", type: "image"}
              - "GradeNat"
              - "Family"
              - "Class"
              - "Attribute"
        Attribute:
          class: App\Entity\Attribute
          image_base_path : '/images/attributes/'
          form:
            fields:
              - "Name"
              - { property: "imageFile", type: "vich_image"}
              - "disadvattribute"
              - "Advantage"
              - "advattribute"
              - "Disadvantage"
              - "mob"
          list:
            fields:
              - "Name"
              - { property: "Image", type: "image"}
              - "disadvattribute"
              - "Advantage"
              - "advattribute"
              - "Disadvantage"
              - "mob"
        Stats:
          class: App\Entity\Stats
    list:
      actions:
        - { name: 'show', icon: 'search', label: '', title: 'Search' }
        - { name: 'edit', icon: 'pencil', label: '', title: 'Edit' }
        - { name: 'delete', icon: 'times', label: '', title: 'Delete' }


